from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QFont

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.NonModal)
        MainWindow.setEnabled(True)
        MainWindow.resize(1280, 900)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralWidget.sizePolicy().hasHeightForWidth())
        self.centralWidget.setSizePolicy(sizePolicy)
        self.centralWidget.setObjectName("centralWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralWidget)
        self.gridLayout.setContentsMargins(11, 11, 11, 11)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.scrollArea = QtWidgets.QScrollArea(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea.sizePolicy().hasHeightForWidth())
        self.scrollArea.setSizePolicy(sizePolicy)
        self.scrollArea.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContentsOnFirstShow)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 1260, 819))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_2.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_2.setSpacing(6)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(11, 11, 250, 11)
        self.horizontalLayout.setSpacing(30)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.actionopen = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.actionopen.setObjectName("actionopen")
        self.horizontalLayout.addWidget(self.actionopen)
        self.openfiles = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.openfiles.setObjectName("openfiles")
        self.horizontalLayout.addWidget(self.openfiles)
        self.label = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.language2 = QtWidgets.QComboBox(self.scrollAreaWidgetContents)
        self.language2.setObjectName("language2")
        self.language2.addItem("")
        self.language2.addItem("")
        self.language2.addItem("")
        self.horizontalLayout.addWidget(self.language2)
        self.translate = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.translate.setObjectName("translate")
        self.horizontalLayout.addWidget(self.translate)
        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(1, 1)
        self.horizontalLayout.setStretch(4, 1)
        self.gridLayout_2.addLayout(self.horizontalLayout, 0, 1, 1, 3)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_3.setSpacing(6)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.eraserlabel = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.eraserlabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.eraserlabel.setObjectName("eraserlabel")
        self.horizontalLayout_3.addWidget(self.eraserlabel)
        self.erasersize = QtWidgets.QComboBox(self.scrollAreaWidgetContents)
        self.erasersize.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.erasersize.setObjectName("erasersize")
        self.erasersize.addItem("")
        self.erasersize.addItem("")
        self.erasersize.addItem("")
        self.erasersize.addItem("")
        self.erasersize.addItem("")
        self.erasersize.addItem("")
        self.erasersize.addItem("")
        self.erasersize.addItem("")
        self.erasersize.addItem("")
        self.erasersize.addItem("")
        self.erasersize.addItem("")
        self.erasersize.addItem("")
        self.erasersize.addItem("")
        self.erasersize.addItem("")
        self.erasersize.addItem("")
        self.erasersize.addItem("")
        self.erasersize.addItem("")
        self.horizontalLayout_3.addWidget(self.erasersize)
        self.fontlabel = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.fontlabel.setTextFormat(QtCore.Qt.AutoText)
        self.fontlabel.setScaledContents(False)
        self.fontlabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.fontlabel.setObjectName("fontlabel")
        self.horizontalLayout_3.addWidget(self.fontlabel)
        self.fontsize = QtWidgets.QComboBox(self.scrollAreaWidgetContents)
        self.fontsize.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.fontsize.setObjectName("fontsize")
        self.fontsize.addItem("")
        self.fontsize.addItem("")
        self.fontsize.addItem("")
        self.fontsize.addItem("")
        self.fontsize.addItem("")
        self.fontsize.addItem("")
        self.fontsize.addItem("")
        self.fontsize.addItem("")
        self.fontsize.addItem("")
        self.fontsize.addItem("")
        self.fontsize.addItem("")
        self.fontsize.addItem("")
        self.fontsize.addItem("")
        self.fontsize.addItem("")
        self.horizontalLayout_3.addWidget(self.fontsize)
        self.gridLayout_2.addLayout(self.horizontalLayout_3, 0, 4, 1, 1)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_3.setSpacing(6)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.gridLayout_2.addLayout(self.verticalLayout_3, 0, 0, 1, 1)
        self.verticalWidget = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.verticalWidget.sizePolicy().hasHeightForWidth())
        self.verticalWidget.setSizePolicy(sizePolicy)
        self.verticalWidget.setStyleSheet("background-color: rgb(220, 220, 220);")
        self.verticalWidget.setObjectName("verticalWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalWidget)
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout.setContentsMargins(5, 5, 5, 470)
        self.verticalLayout.setSpacing(20)
        self.verticalLayout.setObjectName("verticalLayout")
        self.actioneraser = QtWidgets.QPushButton(self.verticalWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.actioneraser.sizePolicy().hasHeightForWidth())
        self.actioneraser.setSizePolicy(sizePolicy)
        self.actioneraser.setMaximumSize(QtCore.QSize(16777215, 50))
        self.actioneraser.setStyleSheet("#actioneraser {\n"
                                        "background-color: transparent;\n"
                                        "border-image: url(./icon_image/eraser.png);\n"
                                        "background: none;\n"
                                        "border: none;\n"
                                        "background-repeat: none;\n"
                                        "}\n"
                                        "\n"
                                        "#actioneraser:pressed\n"
                                        "{\n"
                                        "   border-image: url(./icon_image/eraser.png);\n"
                                        "   border: 3px solid black\n"
                                        "}")
        self.actioneraser.setText("")
        self.actioneraser.setObjectName("actioneraser")
        self.verticalLayout.addWidget(self.actioneraser)
        self.actiontext = QtWidgets.QPushButton(self.verticalWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.actiontext.sizePolicy().hasHeightForWidth())
        self.actiontext.setSizePolicy(sizePolicy)
        self.actiontext.setMaximumSize(QtCore.QSize(16777215, 50))
        self.actiontext.setStyleSheet("#actiontext {\n"
                                      "background-color: transparent;\n"
                                      "border-image: url(./icon_image/T.png);\n"
                                      "background: none;\n"
                                      "border: none;\n"
                                      "background-repeat: none;\n"
                                      "}\n"
                                      "\n"
                                      "#actiontext:pressed\n"
                                      "{\n"
                                      "   border-image: url(./icon_image/T.png);\n"
                                      "   border: 3px solid black\n"
                                      "}")
        self.actiontext.setText("")
        self.actiontext.setObjectName("actiontext")
        self.verticalLayout.addWidget(self.actiontext)
        self.actionundo = QtWidgets.QPushButton(self.verticalWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.actionundo.sizePolicy().hasHeightForWidth())
        self.actionundo.setSizePolicy(sizePolicy)
        self.actionundo.setMaximumSize(QtCore.QSize(16777215, 50))
        self.actionundo.setStyleSheet("#actionundo {\n"
                                      "background-color: transparent;\n"
                                      "border-image: url(./icon_image/undo.png);\n"
                                      "background: none;\n"
                                      "border: none;\n"
                                      "background-repeat: none;\n"
                                      "}\n"
                                      "\n"
                                      "#actionundo:pressed\n"
                                      "{\n"
                                      "   border-image: url(./icon_image/undo.png);\n"
                                      "   border: 3px solid black\n"
                                      "}")
        self.actionundo.setText("")
        self.actionundo.setObjectName("actionundo")
        self.verticalLayout.addWidget(self.actionundo)
        self.actionredo = QtWidgets.QPushButton(self.verticalWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.actionredo.sizePolicy().hasHeightForWidth())
        self.actionredo.setSizePolicy(sizePolicy)
        self.actionredo.setMaximumSize(QtCore.QSize(16777215, 49))
        self.actionredo.setStyleSheet("#actionredo {\n"
                                      "background-color: transparent;\n"
                                      "border-image: url(./icon_image/redo.png);\n"
                                      "background: none;\n"
                                      "border: none;\n"
                                      "background-repeat: none;\n"
                                      "}\n"
                                      "\n"
                                      "#actionredo:pressed\n"
                                      "{\n"
                                      "   border-image: url(./icon_image/redo.png);\n"
                                      "   border: 3px solid black\n"
                                      "}")
        self.actionredo.setText("")
        self.actionredo.setObjectName("actionredo")
        self.verticalLayout.addWidget(self.actionredo)
        self.gridLayout_2.addWidget(self.verticalWidget, 1, 0, 1, 1)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_4.setSpacing(6)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.gridLayout_2.addLayout(self.verticalLayout_4, 2, 0, 2, 1)
        self.label_4 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_4.setGeometry(0, 0, 924, 742)
        self.label_4.setStyleSheet("background:white")
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 1, 1, 1, 3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_2.setContentsMargins(11, 11, 170, 11)
        self.horizontalLayout_2.setSpacing(30)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.download_btn = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.download_btn.setObjectName("download_btn")
        self.horizontalLayout_2.addWidget(self.download_btn)
        self.gridLayout_2.addLayout(self.horizontalLayout_2, 2, 1, 2, 1)
        self.textArea = QtWidgets.QTextEdit(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textArea.sizePolicy().hasHeightForWidth())
        self.textArea.setSizePolicy(sizePolicy)
        self.textArea.setTabletTracking(False)
        self.textArea.setFont(QFont("微軟正黑體", 14))

        self.textArea.setObjectName("textArea")
        self.gridLayout_2.addWidget(self.textArea, 1, 4, 1, 1)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setContentsMargins(200, 11, 11, 11)
        self.horizontalLayout_5.setSpacing(10)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.previous_btn = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.previous_btn.sizePolicy().hasHeightForWidth())
        self.previous_btn.setSizePolicy(sizePolicy)
        self.previous_btn.setStyleSheet("font: 15pt \"華康新綜藝體W9(P)\";")
        self.previous_btn.setObjectName("previous_btn")
        self.horizontalLayout_5.addWidget(self.previous_btn)
        self.pagelist = QtWidgets.QComboBox(self.scrollAreaWidgetContents)
        self.pagelist.setObjectName("pagelist")
        self.horizontalLayout_5.addWidget(self.pagelist)
        self.nextpage_btn = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.nextpage_btn.sizePolicy().hasHeightForWidth())
        self.nextpage_btn.setSizePolicy(sizePolicy)
        self.nextpage_btn.setStyleSheet("font: 15pt \"華康新綜藝體W9(P)\";")
        self.nextpage_btn.setObjectName("nextpage_btn")
        self.horizontalLayout_5.addWidget(self.nextpage_btn)
        self.label_2 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_5.addWidget(self.label_2)
        self.img_num = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.img_num.setObjectName("img_num")
        self.horizontalLayout_5.addWidget(self.img_num)
        self.horizontalLayout_5.setStretch(0, 3)
        self.horizontalLayout_5.setStretch(1, 5)
        self.horizontalLayout_5.setStretch(2, 3)
        self.gridLayout_2.addLayout(self.horizontalLayout_5, 2, 3, 2, 2)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout.addWidget(self.scrollArea, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralWidget)
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "秘密譯師"))
        MainWindow.setWindowIcon(QtGui.QIcon("./icon_image/icon.png"))
        self.actionopen.setText(_translate("MainWindow", "輸入圖片"))
        self.openfiles.setText(_translate("MainWindow", "輸入資料夾"))
        self.label.setText(_translate("MainWindow", "輸出語言："))
        self.language2.setItemText(0, _translate("MainWindow", "中文"))
        self.language2.setItemText(1, _translate("MainWindow", "日文"))
        self.language2.setItemText(2, _translate("MainWindow", "英文"))
        self.translate.setText(_translate("MainWindow", "翻譯"))
        self.eraserlabel.setText(_translate("MainWindow", "橡皮擦："))
        self.erasersize.setItemText(0, _translate("MainWindow", "1"))
        self.erasersize.setItemText(1, _translate("MainWindow", "3"))
        self.erasersize.setItemText(2, _translate("MainWindow", "5"))
        self.erasersize.setItemText(3, _translate("MainWindow", "6"))
        self.erasersize.setItemText(4, _translate("MainWindow", "8"))
        self.erasersize.setItemText(5, _translate("MainWindow", "10"))
        self.erasersize.setItemText(6, _translate("MainWindow", "12"))
        self.erasersize.setItemText(7, _translate("MainWindow", "14"))
        self.erasersize.setItemText(8, _translate("MainWindow", "16"))
        self.erasersize.setItemText(9, _translate("MainWindow", "18"))
        self.erasersize.setItemText(10, _translate("MainWindow", "20"))
        self.erasersize.setItemText(11, _translate("MainWindow", "24"))
        self.erasersize.setItemText(12, _translate("MainWindow", "28"))
        self.erasersize.setItemText(13, _translate("MainWindow", "32"))
        self.erasersize.setItemText(14, _translate("MainWindow", "36"))
        self.erasersize.setItemText(15, _translate("MainWindow", "48"))
        self.erasersize.setItemText(16, _translate("MainWindow", "72"))
        self.erasersize.setCurrentIndex(2)
        self.erasersize.setEditable(True)

        self.fontlabel.setText(_translate("MainWindow", "字型："))
        self.fontsize.setItemText(0, _translate("MainWindow", "8"))
        self.fontsize.setItemText(1, _translate("MainWindow", "10"))
        self.fontsize.setItemText(2, _translate("MainWindow", "12"))
        self.fontsize.setItemText(3, _translate("MainWindow", "14"))
        self.fontsize.setItemText(4, _translate("MainWindow", "16"))
        self.fontsize.setItemText(5, _translate("MainWindow", "18"))
        self.fontsize.setItemText(6, _translate("MainWindow", "20"))
        self.fontsize.setItemText(7, _translate("MainWindow", "22"))
        self.fontsize.setItemText(8, _translate("MainWindow", "24"))
        self.fontsize.setItemText(9, _translate("MainWindow", "26"))
        self.fontsize.setItemText(10, _translate("MainWindow", "28"))
        self.fontsize.setItemText(11, _translate("MainWindow", "36"))
        self.fontsize.setItemText(12, _translate("MainWindow", "48"))
        self.fontsize.setItemText(13, _translate("MainWindow", "72"))
        self.fontsize.setCurrentIndex(2)
        self.fontsize.setEditable(True)
        self.download_btn.setText(_translate("MainWindow", "下載圖片"))
        self.previous_btn.setText(_translate("MainWindow", "←"))
        self.nextpage_btn.setText(_translate("MainWindow", "→"))
        self.label_2.setText(_translate("MainWindow", "目前張數 / 總張數："))
        self.img_num.setText(_translate("MainWindow", "0 / 0"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())